/* Generated by Cython 3.1.2 */

#ifndef __PYX_HAVE__predict_wrapper
#define __PYX_HAVE__predict_wrapper

#include "Python.h"
struct PyTouchPredictor;

/* "predict_wrapper.pyx":15
 * 
 * #
 * cdef public class TouchPredictor [object PyTouchPredictor, type PyTouchPredictorType]:             # <<<<<<<<<<<<<<
 *     cdef object model
 *     cdef object device
*/
struct PyTouchPredictor {
  PyObject_HEAD
  PyObject *model;
  PyObject *device;
};

#ifndef __PYX_HAVE_API__predict_wrapper

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) PyTouchPredictorType;

__PYX_EXTERN_C int initialize_predictor(void);
__PYX_EXTERN_C int finalize_predictor(void);
__PYX_EXTERN_C int create_predictor(char const *);
__PYX_EXTERN_C int predict_touch_data(char const *, char const *);

#endif /* !__PYX_HAVE_API__predict_wrapper */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

/* WARNING: Use PyImport_AppendInittab("predict_wrapper", PyInit_predict_wrapper) instead of calling PyInit_predict_wrapper directly from Python 3.5 */
PyMODINIT_FUNC PyInit_predict_wrapper(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"predict_wrapper\", PyInit_predict_wrapper) instead of calling PyInit_predict_wrapper directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"predict_wrapper\", PyInit_predict_wrapper) instead of calling PyInit_predict_wrapper directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"predict_wrapper\", PyInit_predict_wrapper) instead of calling PyInit_predict_wrapper directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_predict_wrapper_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_predict_wrapper() __PYX_WARN_IF_PyInit_predict_wrapper_INIT_CALLED(PyInit_predict_wrapper())
#endif

#endif /* !__PYX_HAVE__predict_wrapper */
